### ISSUE TITLE
.coffee source?

### ISSUE THREAD

**Issue by franzenzenhofer** [larryng/coffeescript-repl#2]
hi, would love to fork it. but i only see the .js source. is there a .coffee source? would be cool if you would provide it.

**Comment by larryng** [comment]
Nope, no .coffee.  I will likely port it to CoffeeScript soon for practice.
On May 12, 2012 9:15 PM, "Franz" <
reply@reply.github.com>
wrote:

**Comment by larryng** [comment]
Franz, see: https://github.com/larryng/coffeescript-repl/blob/master/coffee/main.coffee

**Comment by franzenzenhofer** [comment]
cool, great thx
